"""init

Revision ID: bbea431917
Revises: None
Create Date: 2017-05-13 07:53:41.702674

"""

# revision identifiers, used by Alembic.
revision = 'bbea431917'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
